const modes = [
  {id:'equation',symbol:'=',name:'Équations',title:'Résoudre une équation',subtitle:'Racines réelles et vérification',placeholder:'2x^2 - 5x + 2 = 0',help:'Saisissez une équation en x. Sans signe =, le second membre vaut 0.',examples:['x^2-5x+6=0','2x^2-5x+2=0','x^3-4x=0']},
  {id:'inequation',symbol:'≤',name:'Inéquations',title:'Résoudre une inéquation',subtitle:'Intervalles de solutions',placeholder:'x^2 - 5x + 6 <= 0',help:'Utilisez <, >, <= ou >= pour les comparaisons.',examples:['x^2-5x+6<=0','(x-1)/(x+2)>0','x^2-4>=0']},
  {id:'simplifier',symbol:'≡',name:'Simplification',title:'Simplifier une expression',subtitle:'Calcul littéral exact',placeholder:'(x^2-1)/(x-1)',help:'Une expression mathématique, sans instruction rédigée.',examples:['(x^2-1)/(x-1)','(sqrt(8)+sqrt(2))','(x+1)^2-x^2']},
  {id:'factoriser',symbol:'()',name:'Factorisation',title:'Factoriser une expression',subtitle:'Produits de facteurs',placeholder:'x^2 - 9',help:'Saisissez le polynôme ou l’expression à factoriser.',examples:['x^2-9','x^3-4x','2x^2+7x+3']},
  {id:'developper',symbol:'↗',name:'Développement',title:'Développer une expression',subtitle:'Développement algébrique',placeholder:'(x+2)(x-3)',help:'Utilisez des parenthèses pour les produits.',examples:['(x+2)(x-3)','(2x-1)^3','(x+y)^2']},
  {id:'derivee',symbol:'ƒ′',name:'Dérivées',title:'Calculer une dérivée',subtitle:'Fonction dérivée et tangente',placeholder:'x^3 - 3x^2 + 2',help:'Optionnel : indiquez un point x₀ pour calculer la tangente.',examples:['x^3-3x^2+2','sin(x)*exp(x)','log(x)/x'],fields:[['point','Point x₀ (facultatif)','']]},
  {id:'integrale',symbol:'∫',name:'Intégrales',title:'Calculer une intégrale',subtitle:'Primitive et intégrale définie',placeholder:'2x + 3',help:'Pour une intégrale définie, renseignez les deux bornes.',examples:['2x+3','sin(x)','1/(1+x^2)'],fields:[['lower','Borne inférieure',''],['upper','Borne supérieure','']]},
  {id:'limite',symbol:'lim',name:'Limites',title:'Calculer une limite',subtitle:'Limites à gauche, à droite et à l’infini',placeholder:'sin(x)/x',help:'Pour ±∞, utilisez inf ou -inf.',examples:['sin(x)/x','(x^2-1)/(x-1)','1/x'],fields:[['point','x tend vers','0'],['side','Direction','+-','select',[['+-','Deux côtés'],['-','Gauche'],['+','Droite']]]]},
  {id:'fonction',symbol:'ƒ',name:'Étude de fonction',title:'Étudier une fonction',subtitle:'Domaine, dérivée, variations et courbe',placeholder:'x^3 - 3x^2 + 2',help:'Analyse symbolique et représentation graphique indicative.',examples:['x^3-3x^2+2','(x+1)/(x-2)','x^2-4x+3']},
  {id:'systeme',symbol:'{ }',name:'Systèmes',title:'Résoudre un système',subtitle:'Deux ou trois équations',placeholder:'2x+y=5; x-y=1',help:'Séparez les équations par ; et utilisez x, y ou z.',examples:['2x+y=5; x-y=1','x+y=7; x-y=1','x+y+z=6; x-y=1; y-z=1']},
  {id:'suite',symbol:'uₙ',name:'Suites numériques',title:'Étudier une suite récurrente',subtitle:'Calcul des termes successifs',placeholder:'(u+3)/4',help:'u désigne le terme précédent. La saisie porte sur u(n+1), pas sur la phrase entière.',examples:['(u+3)/4','2u+1','u/2+3'],fields:[['start','Valeur de u₀','5'],['count','Nombre de termes (1–30)','6']]},
  {id:'statistiques',symbol:'x̄',name:'Statistiques',title:'Analyser des données',subtitle:'Moyenne, médiane, variance, écart-type',placeholder:'10; 12; 15; 18; 20',help:'Séparez les valeurs par des points-virgules, des espaces ou des virgules. Décimales avec un point.',examples:['10; 12; 15; 18; 20','2; 4; 6; 8','12; 14; 14; 15; 20']},
  {id:'complexes',symbol:'i',name:'Nombres complexes',title:'Calculer avec les complexes',subtitle:'Forme algébrique, module et argument',placeholder:'3 + 4i',help:'Utilisez i pour l’unité imaginaire.',examples:['3+4i','(2+i)*(1-3i)','1/(1+i)']},
  {id:'arithmetique',symbol:'ℤ',name:'Arithmétique',title:'Calculer un PGCD et un PPCM',subtitle:'Nombres entiers non négatifs',placeholder:'',help:'Renseignez deux entiers ci-dessous.',examples:[],fields:[['first','Entier a','18'],['second','Entier b','24']]},
  {id:'probabilites',symbol:'P',name:'Probabilités',title:'Loi binomiale',subtitle:'Probabilité P(X=k) et espérance',placeholder:'',help:'Paramètres d’une loi binomiale X ~ B(n,p), avec 0 ≤ k ≤ n.',examples:[],fields:[['first','Nombre d’essais n','10'],['second','Nombre de succès k','3'],['point','Probabilité p (entre 0 et 1)','0.5']]},
  {id:'finance',symbol:'%',name:'Calculs financiers',title:'Intérêts simples et composés',subtitle:'Capital, taux annuel, durée',placeholder:'',help:'Taux à saisir en pourcentage, par exemple 5 pour 5 %.',examples:[],fields:[['first','Capital initial (Ar)','100000'],['point','Taux annuel (%)','5'],['second','Années','3']]}
];

const $ = (id) => document.getElementById(id);
const el = (tag,className='',txt) => {const node=document.createElement(tag);if(className)node.className=className;if(txt!==undefined)node.textContent=txt;return node;};
let current = modes[0], exampleIndex = 0, history = readHistory();
let worker, pending = new Map(), requestId = 0, engineReady = false, loading = false, lastResult = null, timeoutToken = null;

function readHistory(){try{let h=JSON.parse(localStorage.getItem('rm_history_v1')||'[]');return Array.isArray(h)?h.slice(0,20):[];}catch{return [];}}
function writeHistory(){try{localStorage.setItem('rm_history_v1',JSON.stringify(history.slice(0,20)));}catch{/* Le stockage peut être désactivé. */} $('historyCount').textContent=String(history.length);}
function setStatus(message,state=''){ $('engineStatus').textContent=message;$('engineDot').className=`status-dot ${state}`;}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('shown');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('shown'),2600);}
function renderLatex(parent,formula){const math=el('div','math-line');const str=String(formula||'');if(window.katex){try{window.katex.render(str,math,{throwOnError:false,strict:'ignore',trust:false,displayMode:false,maxExpand:100});}catch{math.textContent=str;}}else{math.textContent=str;}parent.appendChild(math);}
function changePage(page){for(const n of ['workspace','history','guide'])$(n+'Page').classList.toggle('hidden',n!==page);document.querySelectorAll('.primary-nav .nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.page===page));$('breadcrumbCurrent').textContent={workspace:'Atelier de résolution',history:'Historique',guide:'Guide de saisie'}[page];$('menuBtn').setAttribute('aria-expanded','false');document.querySelector('.sidebar').classList.remove('open');if(page==='history')renderHistory();window.scrollTo({top:0,behavior:'smooth'});}
function selectMode(id,keepText=false){current=modes.find(m=>m.id===id)||modes[0];document.querySelectorAll('.mode-item').forEach(b=>b.classList.toggle('is-active',b.dataset.mode===current.id));$('selectedModeTitle').textContent=current.title;$('selectedModeSubtitle').textContent=current.subtitle;$('expression').placeholder=current.placeholder||'Les données sont à renseigner ci-dessous';$('expression').disabled=!current.placeholder;$('expression').closest('form').querySelector('.field-label').textContent=current.placeholder?'Expression ou données mathématiques':'Paramètres du problème';$('entryHelp').textContent=current.help;$('extraFields').replaceChildren();for(const field of (current.fields||[])){const [key,label,defaultValue,type,options]=field;const wrapper=el('div','extra-field');const lab=el('label','',label);lab.htmlFor='extra-'+key;const inp=el(type==='select'?'select':'input');inp.id='extra-'+key;inp.dataset.field=key;if(type==='select'){for(const [value,text] of options){const opt=el('option','',text);opt.value=value;inp.appendChild(opt);}}else{inp.type='text';inp.inputMode='decimal';inp.placeholder=defaultValue;inp.value=defaultValue;}wrapper.append(lab,inp);$('extraFields').append(wrapper);}if(!keepText)$('expression').value='';exampleIndex=0;renderExamples();changePage('workspace');}
function renderExamples(){const root=$('examples');root.replaceChildren();$('nextExamples').hidden=current.examples.length<=3;if(!current.examples.length){root.appendChild(el('p','field-help','Renseignez les paramètres pour lancer le calcul.'));return;}for(let i=0;i<Math.min(3,current.examples.length);i++){const formula=current.examples[(i+exampleIndex)%current.examples.length];const b=el('button','example-item');b.type='button';b.append(el('span','',formula),el('span','','→'));b.addEventListener('click',()=>{$('expression').value=formula;$('expression').focus();});root.appendChild(b);}}
function renderModes(){const list=$('modeList');for(const m of modes){const b=el('button','mode-item');b.type='button';b.dataset.mode=m.id;b.append(el('span','',m.symbol),el('strong','',m.name));b.addEventListener('click',()=>selectMode(m.id));list.appendChild(b);}selectMode('equation');}
function makeWorker(){if(worker)worker.terminate();engineReady=false;loading=false;setStatus('Moteur non chargé');worker=new Worker(new URL('./worker.js',import.meta.url));worker.addEventListener('message',ev=>{const msg=ev.data||{};if(msg.type==='status'){setStatus(msg.message,msg.state||'');if(msg.state==='ready')engineReady=true;return;}const item=pending.get(msg.id);if(!item)return;pending.delete(msg.id);clearTimeout(item.timer);if(msg.type==='result')item.resolve(msg.payload);else item.reject(new Error(msg.error||'Erreur du moteur mathématique.'));});worker.addEventListener('error',()=>{setStatus('Moteur indisponible','error');for(const item of pending.values()){clearTimeout(item.timer);item.reject(new Error('Chargement du moteur impossible. Vérifiez votre connexion.'));}pending.clear();});}
function solveInWorker(payload){if(!worker)makeWorker();return new Promise((resolve,reject)=>{const id=++requestId;const timer=setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error('Le moteur ne répond pas. Vérifiez la connexion ou simplifiez le calcul.'));makeWorker();}},engineReady?25000:120000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,type:'solve',payload});});}
function showLoading(){const out=$('output');out.replaceChildren();const block=el('div','loading-state');block.append(el('div','spinner'),el('p','',engineReady?'Calcul et vérification en cours…':'Initialisation du moteur de calcul…'));out.append(block);$('graphBox').hidden=true;$('copyBtn').hidden=true;$('solveBtn').disabled=true;$('solveBtn').firstChild.textContent='Calcul en cours ';}
function showError(message){const out=$('output');out.replaceChildren();const box=el('div','result-error',message);out.append(el('h3','result-title','Calcul non effectué'),box);$('graphBox').hidden=true;$('copyBtn').hidden=true;lastResult=null;}
function showResult(data){if(!data.ok){showError(data.error||'Résolution impossible.');return;}lastResult=data;const out=$('output');out.replaceChildren();const answer=el('div','result-top');answer.append(el('small','','RÉSULTAT FINAL'));for(const ans of data.answers){const wrap=el('div','answer-line');renderLatex(wrap,ans);answer.append(wrap);}out.append(answer);out.append(el('h3','result-title',data.title));if(data.description)out.append(el('p','result-desc',data.description));const steps=el('div','steps-list');for(let i=0;i<data.steps.length;i++){const s=data.steps[i];const block=el('section','step-item');block.append(el('div','step-label',`${String(i+1).padStart(2,'0')}. ${s.label}`));renderLatex(block,s.latex);if(s.note)block.append(el('div','step-note',s.note));steps.append(block);}out.append(steps);$('copyBtn').hidden=false;if(data.plot?.length){$('graphBox').hidden=false;requestAnimationFrame(()=>drawGraph(data.plot));}else $('graphBox').hidden=true;}
function handleForm(){const expr=$('expression').value.trim();if(current.placeholder&&!expr){toast('Saisissez une expression ou choisissez un exemple.');$('expression').focus();return;}const payload={mode:current.id,expression:expr};document.querySelectorAll('#extraFields [data-field]').forEach(inp=>{payload[inp.dataset.field]=inp.value.trim();});showLoading();solveInWorker(payload).then(result=>{showResult(result);if(result.ok){history.unshift({id:Date.now(),mode:current.id,series:$('series').value,expression:expr,extras:Object.fromEntries(Object.entries(payload).filter(([k])=>k!=='mode'&&k!=='expression')),title:current.title,date:new Date().toLocaleString('fr-FR')});history=history.slice(0,20);writeHistory();}}).catch(err=>{showError(err.message||'Erreur inattendue.');setStatus('Chargement à réessayer','error');}).finally(()=>{$('solveBtn').disabled=false;$('solveBtn').firstChild.textContent='Résoudre ';});}
function renderHistory(){const list=$('historyList');list.replaceChildren();if(!history.length){list.append(el('div','history-empty','Aucune résolution enregistrée. Les exercices réussis apparaîtront ici.'));return;}for(const item of history){const card=el('article','history-card');const left=el('div');left.append(el('strong','',item.expression||item.title),el('small','',`${item.title} · Série ${item.series} · ${item.date}`));const b=el('button','','Reprendre →');b.addEventListener('click',()=>{selectMode(item.mode);$('expression').value=item.expression||'';for(const [key,value] of Object.entries(item.extras||{})){const field=$('extraFields').querySelector(`[data-field="${key}"]`);if(field)field.value=value;} $('series').value=item.series||'S';$('expression').focus();});card.append(left,b);list.append(card);}}
function drawGraph(points){const canvas=$('graph');if(!$('graphBox').hidden){const width=canvas.clientWidth||460,height=260,ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,width,height);const usable=points.filter(p=>p&&Number.isFinite(p[1])&&Math.abs(p[1])<100);if(!usable.length)return;const xs=usable.map(p=>p[0]),ys=usable.map(p=>p[1]);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(xmin===xmax){xmin-=1;xmax+=1;}if(ymin===ymax){ymin-=1;ymax+=1;}const pad=28,sx=x=>pad+(x-xmin)/(xmax-xmin)*(width-2*pad),sy=y=>height-pad-(y-ymin)/(ymax-ymin)*(height-2*pad);ctx.strokeStyle='#e6edf3';ctx.lineWidth=1;for(let k=0;k<=8;k++){const xx=pad+(width-2*pad)*k/8;ctx.beginPath();ctx.moveTo(xx,pad);ctx.lineTo(xx,height-pad);ctx.stroke();}for(let k=0;k<=6;k++){const yy=pad+(height-2*pad)*k/6;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(width-pad,yy);ctx.stroke();}ctx.strokeStyle='#a0b3c4';ctx.lineWidth=1.2;const xZero=sx(0),yZero=sy(0);if(xZero>=pad&&xZero<=width-pad){ctx.beginPath();ctx.moveTo(xZero,pad);ctx.lineTo(xZero,height-pad);ctx.stroke();}if(yZero>=pad&&yZero<=height-pad){ctx.beginPath();ctx.moveTo(pad,yZero);ctx.lineTo(width-pad,yZero);ctx.stroke();}ctx.save();ctx.beginPath();ctx.rect(pad,pad,width-2*pad,height-2*pad);ctx.clip();ctx.strokeStyle='#149473';ctx.lineWidth=2.3;ctx.lineJoin='round';ctx.beginPath();let prev=null;for(const p of points){if(!p||p[1]<ymin||p[1]>ymax){prev=null;continue;}const xx=sx(p[0]),yy=sy(p[1]);if(!prev||Math.abs(yy-prev[1])>(height-2*pad)*.68)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy);prev=[xx,yy];}ctx.stroke();ctx.restore();ctx.fillStyle='#8292a5';ctx.font='11px system-ui';ctx.fillText(xmin.toFixed(1),pad,height-8);ctx.fillText(xmax.toFixed(1),width-pad-27,height-8);ctx.fillText(ymax.toFixed(1),5,17);ctx.fillText(ymin.toFixed(1),5,height-28);}}

document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>changePage(b.dataset.page)));
$('menuBtn').addEventListener('click',()=>{const sidebar=document.querySelector('.sidebar');const open=sidebar.classList.toggle('open');$('menuBtn').setAttribute('aria-expanded',String(open));});
document.addEventListener('click',e=>{if(window.innerWidth<=760&&!e.target.closest('.sidebar')&&!e.target.closest('#menuBtn')){document.querySelector('.sidebar').classList.remove('open');$('menuBtn').setAttribute('aria-expanded','false');}});
$('clearBtn').addEventListener('click',()=>{$('expression').value='';$('expression').focus();});
$('nextExamples').addEventListener('click',()=>{exampleIndex++;renderExamples();});
$('mathForm').addEventListener('submit',e=>{e.preventDefault();handleForm();});
document.querySelectorAll('[data-insert]').forEach(b=>b.addEventListener('click',()=>{const input=$('expression');const before=input.value.slice(0,input.selectionStart),after=input.value.slice(input.selectionEnd),text=b.dataset.insert;input.value=before+text+after;input.focus();let pos=before.length+text.length-(text.endsWith('()')?1:0);input.setSelectionRange(pos,pos); }));
$('copyBtn').addEventListener('click',async()=>{if(!lastResult)return;const value=[lastResult.title,...lastResult.steps.map((s,i)=>`${i+1}. ${s.label}\n${s.latex}\n${s.note}`),'Réponse :',...lastResult.answers].join('\n\n');try{await navigator.clipboard.writeText(value);toast('Résolution copiée.');}catch{toast('Copie impossible dans ce navigateur.');}});
$('deleteHistoryBtn').addEventListener('click',()=>{if(history.length&&!confirm('Effacer définitivement l’historique de cet appareil ?'))return;history=[];writeHistory();renderHistory();toast('Historique vidé.');});
window.addEventListener('resize',()=>{if(lastResult?.plot?.length&&!$('graphBox').hidden)drawGraph(lastResult.plot);});
writeHistory();renderModes();makeWorker();
if('serviceWorker' in navigator && location.protocol==='https:')navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
